server:
  port: 9006
credentials:
  id: "2"
  name: "Second-hospital"
  password: "abcd"
hospital-manager:
  address: "http://localhost:9001/"
spring:
  application:
    name: hospital-service

  datasource:
    url: jdbc:mysql://localhost:3306/hospital_two
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    enabled: false