server:
  port: 9001
spring:
  application:
    name: user-auth

  datasource:
    url: jdbc:mysql://localhost:3306/Newdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
